Vagrant.configure("2") do |config|

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "qemu" do |qe|
    qe.arch = "x86_64"
    qe.machine = "pc"
    qe.memory = "512M"
    qe.cpu = "qemu64"
    qe.net_device = "virtio-net-pci"
  end

end

